export {
  DEFAULT_FETCH_TIMEOUT_MS,
  debugLog,
  endTelemetrySpan,
  FetchTimeoutError,
  fetchWithTimeout,
  flushTelemetry,
  isFetchTimeoutError,
  isKnownPkgseerRegistryArg,
  isTelemetryEnabled,
  knownPkgseerRegistryArgs,
  type PkgseerRegistry,
  type PkgseerRegistryArg,
  resetTelemetryCollectorForTests,
  startTelemetrySpan,
  type TelemetryAttributes,
  TelemetryCollector,
  type TelemetrySpanHandle,
  toPkgseerRegistry,
  toPkgseerRegistryLowercase,
  withTelemetrySpan,
  withTelemetrySpanSync,
} from "@githits/core-internal";
export {
  AuthRequiredError,
  type BuildGrepRepoPayloadOptions,
  buildAuthRequiredErrorPayload,
  buildCodeReadCommand,
  buildDocsReadCommand,
  buildGrepRepoParams,
  buildGrepRepoSuccessPayload,
  buildListPackageDocsParams,
  buildListPackageDocsSuccessPayload,
  buildPackageDependenciesParams,
  buildPackageDependenciesSuccessPayload,
  buildPackageSummaryParams,
  buildPackageSummarySuccessPayload,
  buildPackageUpgradeReview,
  buildPackageUpgradeReviewRequest,
  buildPackageVulnerabilitiesParams,
  buildPackageVulnerabilitiesSuccessPayload,
  buildReadPackageDocParams,
  buildReadPackageDocSuccessPayload,
  buildRetryCandidateLine,
  buildSearchHitFollowUpCommand,
  buildTargetResolutionNotes,
  buildUnifiedSearchErrorPayload,
  buildUnifiedSearchParams,
  buildUnifiedSearchStatusPayload,
  buildUnifiedSearchSuccessPayload,
  buildUpgradeDependencyProbeParams,
  type CodeNavigationRegistryArg,
  colorize,
  colors,
  computeBySeverity,
  DEFAULT_WAIT_TIMEOUT_MS,
  type DependencyLifecycle,
  dedupAdvisoriesByAlias,
  dim,
  error,
  extractSolutionId,
  FILE_INTENT_ALL,
  type FileIntentArg,
  type FileIntentInput,
  type FormatGrepRepoTerminalOptions,
  type FormattedGrepRepoTerminal,
  filterLanguages,
  formatAuthRequiredForTerminal,
  formatGrepRepoTerminal,
  formatListPackageDocsTerminal,
  formatPackageDependenciesTerminal,
  formatPackageSummaryTerminal,
  formatPackageUpgradeReviewTerminal,
  formatPackageVulnerabilitiesTerminal,
  formatReadPackageDocTerminal,
  GREP_REPO_PATTERN_NOTE,
  GREP_REPO_SYMBOL_FIELDS,
  GREP_REPO_SYMBOL_FIELDS_NOTE,
  type GrepRepoRequestBuildResult,
  type GrepRepoRequestInput,
  type GrepRepoSymbolField,
  highlight,
  highlightMatch,
  highlightRanges,
  InvalidArgumentError,
  InvalidPackageSpecError,
  isKnownFileIntent,
  isKnownRegistry,
  isKnownSymbolKind,
  isLifecycle,
  KNOWN_REGISTRIES,
  type KnownRegistry,
  knownFileIntentList,
  knownSymbolCategoryList,
  knownSymbolKindList,
  type LanguageMatch,
  type LeanAdvisory,
  type LeanAvailableArtifact,
  type LeanDependencyReport,
  type LeanDirectDependency,
  type LeanFilterBlock,
  type LeanGrepRepoEnvelope,
  type LeanGrepRepoFilter,
  type LeanGrepRepoMatch,
  type LeanGroup,
  type LeanGroupDependency,
  type LeanGroupsBlock,
  type LeanPackageDocEnvelope,
  type LeanPackageDocListEntry,
  type LeanPackageDocsEnvelope,
  type LeanPackageSummary,
  type LeanRuntimeBlock,
  type LeanTargetResolution,
  type LeanTargetResolutionIdentity,
  type LeanTransitiveBlock,
  type LeanVulnerabilityReport,
  type LeanVulnerabilitySummary,
  type LineRange,
  type ListPackageDocsRequestBuildResult,
  type ListPackageDocsRequestInput,
  lowerDocSourceKind,
  MAX_WAIT_TIMEOUT_MS,
  type MappedError,
  type MappedErrorCode,
  mapCodeNavigationError,
  mapPackageIntelligenceError,
  type PackageDependenciesRequestBuildResult,
  type PackageDependenciesRequestInput,
  type PackageSummaryRequestBuildResult,
  type PackageSummaryRequestInput,
  type PackageUpgradeReviewOptions,
  type PackageUpgradeReviewRequestBuildResult,
  type PackageUpgradeReviewRequestInput,
  type PackageVulnerabilitiesRequestBuildResult,
  type PackageVulnerabilitiesRequestInput,
  type ParsedPackageSpec,
  parseCodeNavigationTargetSpec,
  parseLinesOption,
  parsePackageSpec,
  parseUnifiedSearchTargetSpec,
  projectTargetResolution,
  type ReadPackageDocRequestBuildResult,
  type ReadPackageDocRequestInput,
  renderGrepRepoText,
  renderListFilesText,
  renderListPackageDocsText,
  renderReadFileText,
  renderReadPackageDocText,
  renderUnifiedSearchError,
  renderUnifiedSearchStatusText,
  renderUnifiedSearchSuccess,
  requireAuth,
  SEVERITY_LABEL_TO_CVSS,
  type SeverityLabel,
  type SymbolCategoryArg,
  severityLabel,
  shouldUseColors,
  success,
  supportsDependenciesRegistry,
  supportsVulnerabilitiesRegistry,
  toCodeNavigationRegistry,
  toFileIntent,
  toSymbolCategory,
  toSymbolKind,
  type UnifiedSearchCompletedPayload,
  type UnifiedSearchErrorPayload,
  type UnifiedSearchHitPayload,
  type UnifiedSearchIncompletePayload,
  type UnifiedSearchQueryEcho,
  type UnifiedSearchRequestBuildResult,
  type UnifiedSearchRequestInput,
  type UnifiedSearchStatusCompletedPayload,
  type UnifiedSearchStatusIncompletePayload,
  type UnifiedSearchStatusResultPayload,
  UnsupportedDependenciesRegistryError,
  UnsupportedRegistryError,
  UnsupportedVulnerabilitiesRegistryError,
  type UpgradeAdvisorySummary,
  type UpgradeChangelog,
  type UpgradeChangelogEntry,
  type UpgradeCompatibility,
  type UpgradeDependencyChangeGroup,
  type UpgradeDependencyChangeItem,
  type UpgradeDependencyChanges,
  type UpgradeDependencyIssues,
  type UpgradeReview,
  type UpgradeReviewPackageInput,
  type UpgradeReviewPackageRequest,
  type UpgradeReviewResponse,
  type UpgradeSecurity,
  type UpgradeTransitiveSecurity,
  type UpgradeTransitiveVulnerablePackage,
  type VersionDelta,
  type VersionVulnerabilitySummary,
  type VulnSeverityLabel,
  vulnSeverityLabel,
  warning,
} from "@githits/mcp/internal";
export { parseIntCliOption, parsePortCliOption } from "./cli-options.js";
export {
  InvalidKeywordsError,
  normaliseKeywords,
} from "./normalise-keywords.js";
export {
  createRootCliPreAction,
  type RootCliPreActionDependencies,
} from "./root-cli-pre-action.js";
export { type Spinner, startSpinner } from "./spinner.js";
export { SPINNER_MESSAGES } from "./spinner-messages.js";
