// Serialized from the backend AgenticAskNeedsTargetResponse contract.
export const ASK_NEEDS_TARGET_WIRE = {
  outcome: "needs_target",
  message:
    "GitHits could not determine a target for the question with high enough confidence. Did you mean any of these? Follow up with a specific target.",
  resolution: {
    best: {
      kind: "REPOSITORY",
      canonicalKey: "github:openai/codex",
      confidence: "MEDIUM",
    },
    protectedMatches: [
      {
        kind: "PACKAGE",
        canonicalKey: "npm:codex",
        confidence: "MEDIUM",
      },
    ],
    targets: [
      {
        kind: "REPOSITORY",
        canonicalKey: "github:openai/codex",
        latestVersionMaliciousStatus: "NOT_APPLICABLE",
        docsAvailable: false,
        codeAvailable: true,
        description: "Lightweight coding agent that runs in your terminal",
        repositoryUrl: "https://github.com/openai/codex",
        stars: 122000,
        downloadsLastMonth: null,
        downloadsTotal: null,
        groupKey: "github:openai/codex",
        match: {
          confidence: "MEDIUM",
        },
        docsPageCount: null,
        codeFileCount: 7200,
        license: null,
        latestVersionMaliciousEvidence: null,
      },
      {
        kind: "PACKAGE",
        canonicalKey: "npm:@openai/codex",
        latestVersionMaliciousStatus: "CLEAR",
        docsAvailable: false,
        codeAvailable: true,
        description: "Codex CLI is a coding agent from OpenAI.",
        repositoryUrl: null,
        stars: null,
        downloadsLastMonth: 76000000,
        downloadsTotal: null,
        groupKey: "github:openai/codex",
        match: {
          confidence: "MEDIUM",
        },
        docsPageCount: null,
        codeFileCount: null,
        license: "Apache-2.0",
        latestVersionMaliciousEvidence: null,
      },
      {
        kind: "PACKAGE",
        canonicalKey: "npm:codex",
        latestVersionMaliciousStatus: "CLEAR",
        docsAvailable: false,
        codeAvailable: false,
        description: "Static site and code documentation generator.",
        repositoryUrl: null,
        stars: null,
        downloadsLastMonth: 46000,
        downloadsTotal: null,
        groupKey: null,
        match: {
          confidence: "MEDIUM",
        },
        docsPageCount: null,
        codeFileCount: null,
        license: null,
        latestVersionMaliciousEvidence: null,
      },
    ],
    targetsTruncated: true,
    ambiguous: true,
    ambiguousReason: "MULTIPLE_MATCHES",
  },
};
